baseURL = "/"
languageCode = "zh-cn"
title = "Home"
theme = "book"
publishdir = "."
defaultContentLanguage = "cn"
disqusShortname = "jchby"

# Book configuration
disablePathToLower = true
enableGitInfo = true

[languages]
[languages.cn]
  languageName = 'Chinese'
  contentDir = 'content'
  weight = 1

[params]
    BookToC = 3
    BookLogo = 'logo.png'
